### ISSUE TITLE
Withdraw Function Issue

### ISSUE THREAD

**Issue by DS-Coding0** [Cyfrin/foundry-fund-me-cu#75]
I'm done verify my Fund Me Contract, now i have some ETH on my Contract Address and i want to withdraw this ETH.

Contract Address: 0x2e083Ef88c2e042185eF1f86eDDd1D7a06ae4429

i had try with this command:
```
forge script script/Interactions.s.sol:WithdrawFundMe --rpc-url $SEPOLIA_RPC_URL --account MetaMaskSep --broadcast
```
but get this error:
```
[⠒] Compiling...
No files changed, compilation skipped
Traces:
  [939479] → new WithdrawFundMe@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    └─ ← [Return] 4582 bytes of code

  [3394] WithdrawFundMe::run()
    ├─ [0] VM::readDir("./broadcast", 3) [staticcall]
    │   └─ ← [Revert] the path broadcast is not allowed to be accessed for read operations
    └─ ← [Revert] the path broadcast is not allowed to be accessed for read operations


Error: 
script failed: the path broadcast is not allowed to be accessed for read operations
```
I don't know where the 0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519 Contract ID come from.. thats on new WithdrawFundMe@.

Any solutions for this problem?

**Comment by UmitRock** [comment]
dear check out my repo all codes updated 2024 may https://github.com/UmitRock/Hardhat-Fund-Me-2024-May-Updated

**Comment by UmitRock** [comment]
dear check out my repo all codes updated 2024 April https://github.com/UmitRock/Foundry-fund-Me-2024-April-Updated

**Comment by DS-Coding0** [comment]
> dear check out my repo all codes updated 2024 April https://github.com/UmitRock/Foundry-fund-Me-2024-April-Updated

That doesn't help me in this case.. code look very similar like mine.

**Comment by cromewar** [comment]
Hello @DS-Coding0.

Please check you have the env variables for Sepolia ($SEPOLIA_RPC_URL ) added correctly, also can you share your script code here?

**Comment by DS-Coding0** [comment]
My complete code is in my repo.

What I find out is, if i manually work with the contract over sepolia etherscan everything works perfect.

**Comment by DS-Coding0** [comment]
> @DS-Coding0  thats mean have problem on ur pc or nertwork sepolia slow sometimes and all code i modified and work perfectly

I don't think that's a problem with my PC.. if I want to withdraw via forge script I get the error which I posted in the issue.. but if I withdraw over sepolia etherscan there's no problem.

**Comment by PatrickAlphaC** [comment]
Please add this to your `foundry.toml` and it should fix the issue:

```
fs_permissions = [{ access = "read", path = "./broadcast" }]
```

What section of the course were you on when you ran into this?

**Comment by DS-Coding0** [comment]
I'm am Lesson 7 : Foundry Fund Me
Around 2 Hours i think.. 

Tried to add this to my foundry.toml.. i get this error now if i want to withdraw:
```
[3394] WithdrawFundMe::run()
    ├─ [0] VM::readDir("./broadcast", 3) [staticcall]
    │   └─ ← [Revert] the path broadcast is not allowed to be accessed for read operations
    └─ ← [Revert] the path broadcast is not allowed to be accessed for read operations
```

my WithdrawFundMe is this:
```
contract WithdrawFundMe is Script {
function withdrawFundMe(address mostRecentlyDeployed) public {
    vm.startBroadcast();
    FundMe(payable(mostRecentlyDeployed)).withdraw();
    vm.stopBroadcast();
    console.log("Withdraw FundMe balance!");
}
```

**Comment by PatrickAlphaC** [comment]
Hmmm. Could you update the forge-std to version 1.8.2?

**Comment by DS-Coding0** [comment]
> Hmmm. Could you update the forge-std to version 1.8.2?

If I have seen correctly, I already have version 1.8.2

**Comment by PatrickAlphaC** [comment]
I'm unable to reproduce this issue. I'm about to revamp this repo soon though. Stay tuned.

**Comment by DS-Coding0** [comment]
> I'm unable to reproduce this issue. I'm about to revamp this repo soon though. Stay tuned. 

That would be great.. I mean I can interact with the contract over etherscan with no problems. But directly in vsc I can't use the withdraw function.
