### ISSUE TITLE
Contract Deployment Increased Cost for Sepolia

### ISSUE THREAD

**Issue by mumernisar** [Cyfrin/foundry-fund-me-cu#84]
While deploying to Sepolia, you might sometimes receive " Insufficient funds," and it is difficult to obtain more Sepolia ETH. 
A new test-net by the name of Holesky is live.
I would love to contribute and add it to the project.
Currently, a chainlink price feed contract doesn't exist for Holesky, but eOracle has one. It can be implemented through the same AggregatorV3Interface, so there are no major changes.
If this change would be welcome, let me know so I can fork and make a pull request.

**Comment by Equious** [comment]
I agree, Sepolia is having issues lately. I'm unsure how we'll handle test nets, but there's been talk of setting up something ourselves as a longer term solution.

Appreciate the suggestion!
