### ISSUE TITLE
I find that no parameters are passed in DeployFundMe at new FundMe(), but there is no error message 

### ISSUE THREAD

**Issue by lazyccx** [Cyfrin/foundry-fund-me-cu#89]
![image](https://github.com/user-attachments/assets/9746a3a1-3e8a-4960-9160-de9db6ce301a)
![image](https://github.com/user-attachments/assets/da5dc0c7-2e2f-42ed-a788-dd00bedb87e9)

When I follow this procedure, I find that no parameters are passed in DeployFundMe at new FundMe(), but there is no error message prompted in vscode, the environment is windows 11, and the Solidity by Nomic Foundation plugin is installed.

I hope you can help me find the problem，extremely grateful

**Comment by Equious** [comment]
Hey, this isn't the best place to find support with the course. I recommend searching the discussions tab or joining us in the [discord ](https://discord.gg/5SUpnQJs) server.

I would expect the deployment to fail without parameters.
